name: FixMate CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout FixMate repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytest
        run: pip install pytest

      - name: Run automated tests
        run: pytest -v

      - name: Run FixMate application
        run: python fixmate.py
